// Melo/Settings/Types/SettingsUITypes.swift
import Foundation
import AppKit

// MARK: - App-Wide Settings Enums

enum MenuBarIconStyle: String, Codable, CaseIterable, Identifiable {
    case `default` = "Default"
    case classicMark = "Classic Mark"
    case speaker = "Speaker"
    case device = "Device"
    case waveform = "Waveform"
    case equalizer = "Equalizer"

    var id: String { rawValue }

    /// The icon name - either asset catalog name or SF Symbol
    var iconName: String {
        switch self {
        case .default: return "Melo mark"
        case .classicMark: return "Melo mark (smooth)"
        case .speaker: return "speaker.wave.2.fill"
        case .device: return "headphones"
        case .waveform: return "waveform"
        case .equalizer: return "slider.vertical.3"
        }
    }

    var isSystemSymbol: Bool {
        self != .default && self != .classicMark
    }
}

// MARK: - HUD Style

/// Style of the on-screen HUD shown when media keys drive Melo's volume.
/// `.tahoe` renders a small top-right pill; `.classic` renders a center-bottom panel
/// with 16 segment tiles matching Apple's pre-Tahoe HUD aesthetic.
enum HUDStyle: String, Codable, CaseIterable, Identifiable {
    case tahoe
    case classic

    var id: String { rawValue }
}

// MARK: - Appearance Preference

/// User preference for app appearance. `.system` follows macOS appearance live;
/// `.light` and `.dark` lock the override regardless of system setting.
enum AppearancePreference: String, Codable, CaseIterable, Identifiable, CustomStringConvertible {
    case system
    case light
    case dark

    var id: String { rawValue }

    var description: String {
        switch self {
        case .system: return "System"
        case .light: return "Light"
        case .dark: return "Dark"
        }
    }
}

// MARK: - Melo Visual Theme

/// Decorative palette layered over the user's light/dark appearance choice.
/// System Accent is the default and follows the Mac's current accent color.
enum MeloVisualTheme: String, Codable, CaseIterable, Identifiable, CustomStringConvertible {
    case systemAccent
    case space
    case galaxy
    case aurora
    case custom
    case aiGenerated

    var id: String { rawValue }

    var description: String {
        switch self {
        case .systemAccent: return "Mac"
        case .space: return "Space"
        case .galaxy: return "Galaxy"
        case .aurora: return "Aurora"
        case .custom: return "Custom"
        case .aiGenerated: return "AI Theme"
        }
    }

    var symbolName: String {
        switch self {
        case .systemAccent: return "apple.logo"
        case .space: return "moon.stars.fill"
        case .galaxy: return "sparkles"
        case .aurora: return "mountain.2.fill"
        case .custom: return "paintpalette.fill"
        case .aiGenerated: return "wand.and.stars"
        }
    }

    var prefersDarkAppearance: Bool {
        switch self {
        case .space, .galaxy, .aurora, .aiGenerated:
            return true
        case .systemAccent, .custom:
            return false
        }
    }
}

/// A constrained, data-only theme that can be generated by OpenAI or pasted
/// from ChatGPT. Themes never contain Swift, scripts, file paths, or arbitrary
/// assets. This keeps AI customization inside Melo's existing visual frame.
nonisolated struct GeneratedMeloTheme: Codable, Equatable, Sendable {
    enum Style: String, Codable, CaseIterable, Sendable {
        case stars
        case aurora
        case nebula
        case gradient
    }

    var name: String
    var style: Style
    var accentHex: String
    var topHex: String
    var middleHex: String
    var bottomHex: String
    var secondaryHex: String
    var starDensity: Int
    var sparkleStrength: Double
    var showsRocket: Bool

    static let fallback = GeneratedMeloTheme(
        name: "Midnight Signal",
        style: .stars,
        accentHex: "#6DB7FF",
        topHex: "#07142E",
        middleHex: "#10163B",
        bottomHex: "#02040B",
        secondaryHex: "#E45B5B",
        starDensity: 24,
        sparkleStrength: 0.16,
        showsRocket: true
    )

    var normalized: GeneratedMeloTheme {
        GeneratedMeloTheme(
            name: Self.cleanedName(name),
            style: style,
            accentHex: Self.cleanedHex(accentHex, fallback: Self.fallback.accentHex),
            topHex: Self.cleanedHex(topHex, fallback: Self.fallback.topHex),
            middleHex: Self.cleanedHex(middleHex, fallback: Self.fallback.middleHex),
            bottomHex: Self.cleanedHex(bottomHex, fallback: Self.fallback.bottomHex),
            secondaryHex: Self.cleanedHex(secondaryHex, fallback: Self.fallback.secondaryHex),
            starDensity: min(max(starDensity, 0), 48),
            sparkleStrength: min(max(sparkleStrength, 0.04), 0.28),
            showsRocket: showsRocket
        )
    }

    private static func cleanedName(_ value: String) -> String {
        let cleaned = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return fallback.name }
        return String(cleaned.prefix(32))
    }

    private static func cleanedHex(_ value: String, fallback: String) -> String {
        let cleaned = value.trimmingCharacters(in: CharacterSet.alphanumerics.inverted).uppercased()
        guard cleaned.count == 6, cleaned.allSatisfy({ $0.isHexDigit }) else { return fallback }
        return "#" + cleaned
    }
}

extension AppearancePreference {
    /// AppKit appearance override. `nil` means "inherit from window or app".
    /// Apply via `nsView.window?.appearance = value` for any `NSWindow`/`NSPanel`
    /// the app hosts (popup, popover, HUD).
    /// `.aqua` available since macOS 10.9; `.darkAqua` since 10.14.
    var nsAppearance: NSAppearance? {
        switch self {
        case .system: return nil
        case .light: return NSAppearance(named: .aqua)
        case .dark: return NSAppearance(named: .darkAqua)
        }
    }
}

// MARK: - Menu Bar Popup Size

enum MenuBarPopupSize: String, Codable, CaseIterable, Identifiable, CustomStringConvertible {
    case compact
    case comfortable
    case spacious

    var id: String { rawValue }

    var description: String {
        switch self {
        case .compact: return "Compact"
        case .comfortable: return "Comfortable"
        case .spacious: return "Spacious"
        }
    }
}

struct PopupDimensions: Equatable {
    let width: CGFloat
    let contentPadding: CGFloat
    /// Ceiling on the scrollable body. Sized to stay within a 13" MacBook Air's
    /// usable height after the menu bar, since FluidMenuBarExtra does not clamp
    /// the popup against `screen.visibleFrame` vertically.
    let maxContentHeight: CGFloat
}

extension MenuBarPopupSize {
    var dimensions: PopupDimensions {
        switch self {
        case .compact:
            return PopupDimensions(
                width: 470,
                contentPadding: 12,
                maxContentHeight: 560
            )
        case .comfortable:
            return PopupDimensions(
                width: 510,
                contentPadding: 16,
                maxContentHeight: 660
            )
        case .spacious:
            return PopupDimensions(
                width: 560,
                contentPadding: 20,
                maxContentHeight: 760
            )
        }
    }
}

// MARK: - Volume Hotkey Step Size

enum VolumeHotkeyStep: String, Codable, CaseIterable, Identifiable, CustomStringConvertible {
    case coarse
    case normal
    case fine
    case extraFine

    var id: String { rawValue }

    var sliderDelta: Double {
        switch self {
        case .coarse:    return 1.0 / 8.0
        case .normal:    return 1.0 / 16.0
        case .fine:      return 1.0 / 32.0
        case .extraFine: return 1.0 / 64.0
        }
    }

    var description: String {
        switch self {
        case .coarse:    return "Coarse (12.5%)"
        case .normal:    return "Normal (6.25%)"
        case .fine:      return "Fine (3.13%)"
        case .extraFine: return "Extra-Fine (1.56%)"
        }
    }
}

// MARK: - Menu Bar Information

/// Optional plain-language information shown beside Melo's menu bar icon.
/// The default remains icon-only so existing installations do not change shape.
enum MenuBarInfoStyle: String, Codable, CaseIterable, Identifiable, CustomStringConvertible {
    case iconOnly
    case volume
    case device
    case level

    var id: String { rawValue }

    var description: String {
        switch self {
        case .iconOnly: return "Icon Only"
        case .volume: return "Volume"
        case .device: return "Device"
        case .level: return "Live Level"
        }
    }

    var symbolName: String {
        switch self {
        case .iconOnly: return "circle"
        case .volume: return "percent"
        case .device: return "headphones"
        case .level: return "waveform"
        }
    }
}
